language: node_js
node_js:
  - '8'

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - URI_SCHEME: http
    - CNAME: dojocon2017.coderdojo.jp
    - BASEURL: ''
    - GIT_USER: Kite
    - GIT_EMAIL: ixkaito@gmail.com
    - GITHUB_RELEASE_REPO: dojocon-japan/dojocon2017.coderdojo.jp
    - RELEASE_BRANCH: &release_branch release

branches:
  only:
    - master
    - *release_branch

before_install:
  - rvm install 2.4.1

install:
  - npm install
  - gem install jekyll html-proofer

script:
  - jekyll build
  - npm test
  - htmlproofer ./_site --check-html --url-ignore "/jp\.linkedin\.com\/in\/tomomikosaka/","/mymckok\.tumblr\.com/","/facebook\.com/","/mainichi\.jp/"
  - if [ "$TRAVIS_PULL_REQUEST" != "false" -o "$TRAVIS_BRANCH" != "$RELEASE_BRANCH" ]; then exit 0; fi
  - if [ ! -f CNAME ]; then touch CNAME; fi
  - echo $CNAME > CNAME
  - echo url:\ ${URI_SCHEME}://${CNAME} >> _config.yml

after_success:
  - git config user.name "${GIT_USER}"
  - git config user.email "${GIT_EMAIL}"
  - git add --all && git commit -m "Deploy from Travis CI"
  - git push -f -q "https://${GITHUB_TOKEN}@github.com/${GITHUB_RELEASE_REPO}.git" HEAD:gh-pages > /dev/null 2>&1

sudo: false
