# Welcome to Frasco!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DojoCon Japan 2017 - つながる Dojo to Dojo -
description: DojoCon Japanは日本のCoderDojo関係者（見守る大人、学ぶ子供）とその活動に賛同・協賛する人が全国各地から集まる大きなイベントです。
baseurl: "" # the subpath of your site, e.g. /blog
url: https://dojocon-japan.github.io

sponsorform_url: https://docs.google.com/forms/d/e/1FAIpQLSfL3xYPIzWNKMhaVIiuiXgAT87nli91wamru6RcuS1zosb6QQ/viewform
contactform_url: https://docs.google.com/forms/d/e/1FAIpQLScqnV4pU-sCiXkrL3JzLjDdJ_GDBye0v91jH_w5-9giE31QdQ/viewform

twitter:
  id: DojoConJapan
  hashtag: DojoConJP

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - frasco.config.js
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package.json
  - README.md

compress_html:
  clippings: all
  comments: all
  endings: all
  # ignore:
  #   envs: [development]
  # blanklines: true
  # profile: true
  startings: [html, head, body]
url: http://dojocon2017.coderdojo.jp
url: http://dojocon2017.coderdojo.jp
